############################################################
# Dockerfile to build sandbox for executing user code
# Based on Ubuntu
############################################################

FROM ubuntu

#Install all the languages/compilers we are supporting.
RUN apt update
RUN apt install build-essential -y
RUN apt install bc -y